name: "Push Daily Experimental Tag"
on:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:
jobs:
  push-tag:
    name: Push Release Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push tag
        run: |
          DAY=$(date "+%Y-%m-%d")
          git tag experimental-$DAY
          git push -f origin experimental-$DAY
